---
# Main playbook for deploying Kubernetes cluster

- name: Deploy Kubernetes Cluster
  hosts: all
  become: true
  vars_files:
    - vars/all.yml
  roles:
    - environment
    - dependencies
    - kubernetes_repo
    - haproxy
    - keepalived
    - kubernetes_master
    - kubernetes_worker
