# Main playbook file for deploying Kubernetes cluster

- import_playbook: tasks/environment.yml
- import_playbook: tasks/dependencies.yml
- import_playbook: tasks/kubernetes_repo.yml
- import_playbook: tasks/haproxy.yml
- import_playbook: tasks/keepalived.yml
- import_playbook: tasks/kubernetes_master.yml
- import_playbook: tasks/kubernetes_worker.yml