---
- name: Configure HTTP Proxy
  lineinfile:
    path: /etc/environment
    regexp: '^HTTP_PROXY='
    line: "HTTP_PROXY={{ proxy_http }}"

- name: Configure HTTPS Proxy
  lineinfile:
    path: /etc/environment
    regexp: '^HTTPS_PROXY='
    line: "HTTPS_PROXY={{ proxy_https }}"

- name: Export Proxy Settings for Current Shell
  shell: |
    echo "export HTTP_PROXY={{ proxy_http }}" >> /etc/profile
    echo "export HTTPS_PROXY={{ proxy_https }}" >> /etc/profile
