---
- name: Create Directory for Apt Keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Kubernetes Apt Key
  shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

    
- name: Add Kubernetes Apt Repository
  shell: |
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /" > /etc/apt/sources.list.d/kubernetes.list

- name: Update APT Cache
  apt:
    update_cache: yes

- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Hold Kubernetes Packages
  shell: "apt-mark hold kubelet kubeadm kubectl"

- name: Enable Kubelet Service
  service:
    name: kubelet
    enabled: true
    state: started
