---
- name: Create Diretory
  shell: "sudo mkdir -p -m 755 /etc/apt/keyrings"

- name: Add Kubernetes Apt Key
  shell: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Add Kubernetes Apt Repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install Kubernetes Tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Hold Kubernetes Packages
  shell: "apt-mark hold kubelet kubeadm kubectl"
